package dev.vicky.spring_ai.chat;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import reactor.core.publisher.Flux;

/**
 * Controller for basic chat interactions with the LLM.
 * Supports standard chat, streaming responses, and simple chat response
 * objects.
 */
@RestController
public class ChatController {

	private final ChatClient chatClient;

	public ChatController(@Qualifier("googleChatClient") final ChatClient chatClient) {

		this.chatClient = chatClient;
	}

	/**
	 * Basic chat endpoint that returns information about Java.
	 *
	 * @return A string containing information about Java generated by the LLM.
	 */
	@GetMapping("/chat")
	public String chat() {
		return this.chatClient.prompt()
				.user("Tell me something about Java")
				.call()
				.content();
	}

	/**
	 * Streaming chat endpoint that provides a real-time list of places to visit in
	 * Himachal.
	 *
	 * @return A Flux of tokens from the LLM response.
	 */
	@GetMapping(value = "/stream")
	public Flux<String> stream() {
		return this.chatClient.prompt()
				.user("I am visiting Himachal next year. Please tell me 10 interesting places to visit and enjoy the trip.")
				.stream()
				.content();
	}

	/**
	 * Endpoint that returns a ChatResponse containing a joke.
	 *
	 * @return A full ChatResponse object from the LLM.
	 */
	@GetMapping("/joke")
	public ChatResponse chatResponse() {
		return this.chatClient.prompt()
				.user("Tell me a good joke !")
				.call()
				.chatResponse();
	}

}
